wandb_version: 1

learning_rate:
  desc: null
  value: 0.0003
architecture:
  desc: null
  value: VAE
dataset:
  desc: null
  value: data/debug_run/ImageDataSet
epochs:
  desc: null
  value: 5000
_wandb:
  desc: null
  value:
    python_version: 3.10.4
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1697554713.471325
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.4
      5: 0.15.8
      8:
      - 5
